### ISSUE TITLE
Unicode bug

### ISSUE THREAD

**Issue by trbjo** [robwalton/alfred-ulysses-workflow#5]
Whenever I try to use Danish letters æøå to search for items in the workflow I get thrown back to the Alfred fallback option. It's not limited to æøå, the ordering of letters is of no importance either and it doesn't matter which combination I use (uf, us, ug).

**Comment by trbjo** [comment]
The debug log is here:

Starting debug for 'Ulysses'

[2017-08-24 23:08:48][STDERR: input.scriptfilter] ulysses_items.py:124: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (os.path.exists(args.limit_scope_dir),
23:08:48 workflow.py:2225 DEBUG    Workflow version : 1.0.0
23:08:48 workflow.py:1628 DEBUG    Reading settings from `/Users/troels/Library/Application Support/Alfred 3/Workflow Data/com.github.robwalton.alfred-ulysses-workflow/settings.json` ...
23:08:48 workflow.py:2514 DEBUG    Update check not due
23:08:48 ulysses_items.py:57 INFO     ulysses_items.main(wf): args = 
Namespace(kind='all', limit_scope_dir=None, query='', search_content=True, search_ulysses_path=False)
23:08:48 workflow.py:1859 DEBUG    Loading cached data from : /Users/troels/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.github.robwalton.alfred-ulysses-workflow/__workflow_update_status.cpickle
23:08:48 workflow.py:2444 DEBUG    update_data : {u'available': False}
23:08:48 ulysses_items.py:82 INFO     Added iCloud items from '/Users/troels/Library/Mobile Documents/X5AZV975AG~com~soulmen~ulysses3/Documents/Library/Groups-ulgroup'
23:08:48 ulysses_items.py:82 INFO     Added iCloud Inbox items from '/Users/troels/Library/Mobile Documents/X5AZV975AG~com~soulmen~ulysses3/Documents/Library/Unfiled-ulgroup'
23:08:48 ulysses_items.py:89 INFO     No local items found at '/Users/troels/Library/Containers/com.soulmen.ulysses3/Data/Documents/Library/Groups-ulgroup'
23:08:48 ulysses_items.py:89 INFO     No local Inbox items found at '/Users/troels/Library/Containers/com.soulmen.ulysses3/Data/Documents/Library/Unfiled-ulgroup'
23:08:48 workflow.py:2423 DEBUG    Set last run version : 1.0.0
23:08:48 workflow.py:2267 DEBUG    Workflow finished in 0.536 seconds.
[2017-08-24 23:08:50][ERROR: input.scriptfilter] Code 2: ulysses_items.py:124: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (os.path.exists(args.limit_scope_dir),
23:08:50 workflow.py:2225 DEBUG    Workflow version : 1.0.0
23:08:50 workflow.py:1628 DEBUG    Reading settings from `/Users/troels/Library/Application Support/Alfred 3/Workflow Data/com.github.robwalton.alfred-ulysses-workflow/settings.json` ...
23:08:50 workflow.py:2514 DEBUG    Update check not due
usage: ulysses_items.py [-h] [--kind [KIND]]
                        [--limit-scope-to-dir [LIMIT_SCOPE_DIR]]
                        [--search-content] [--search-ulysses-path]
                        [query]
ulysses_items.py: error: argument query: invalid str value: u'\xe6'
23:08:50 workflow.py:2267 DEBUG    Workflow finished in 0.020 seconds.

**Comment by robwalton** [comment]
I've made a draft release to fix this bug. Maybe you could try it out. It looks good a first glance to me.

[draft 1.0.3](https://github.com/robwalton/alfred-ulysses-workflow/releases/download/untagged-76cb1e761cae62d95c90/Ulysses.alfredworkflow)

**Comment by robwalton** [comment]
Immediate bug fixed and it seems to find notes with the Danish letters æøå. Uploaded to packal as v1.0.3
