### ISSUE TITLE
Add support to search external folders too (include it in Group search)

### ISSUE THREAD

**Issue by nikivdev** [robwalton/alfred-ulysses-workflow#6]
In Ulysses you can add external folders to edit files from Ulysses. I wish I could jump to these folders too from the workflow.

**Comment by nikivdev** [comment]
Actually that's fine. I can make a dedicated file filter search for that in Alfred. 🙂

**Comment by robwalton** [comment]
Hi @nikitavoloboev, I started adding support for external folders, but I don't really have time to commit to supporting it right now. We had some weird differences of the database representation on disk which appeared to be dependent on which Ulysses version first created it -- I dropped it at this point. I'll be using Ulysses a lot more for a bit, so you never know though.
